name: CI-CD

on:
  push:
    branches: ["main"]

jobs: 
  Ci: 
    runs-on: ubuntu-latest
    
    steps:   
    - uses: actions/checkout@v4.2.2

    - name: Autenticação Docker hub
      uses: docker/login-action@v3.4.0
      with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
    - name: construindo imagem docker 
      uses: docker/build-push-action@v6.18.0
      with: 
        context: ./ci_cd_na_pratica
        file: ./ci_cd_na_pratica/Dockerfile
        push: true
        tags: |
          kaualcaya/aprendizado:v1
          kaualcaya/aprendizado:latest


    
